.PHONY: all alp pt-query-digest other

all: alp pt-query-digest other

alp:
	sudo install bin/alp /usr/alp

pt-query-digest:
	sudo yum install rpm/percona-release-0.1-6.noarch.rpm

other:
	sudo yum install -y dstat tmux vim
